changelog:
  repository: spring-io/github-changelog-generator
  contributors:
    title: "Contributors"
  sections:
    - title: "Highlights"
      labels: [ "noteworthy" ]
      group: "highlights"
    - title: "Enhancements"
      labels: [ "new" ]
    - title: "Bugs"
      labels: [ "fix" ]
  issues:
    ports:
      - label: "status: forward-port"
        bodyExpression: 'Forward port of issue #(\d+).*'
      - label: "status: backport"
        bodyExpression: 'Back port of issue #(\d+).*'
  external_links:
    - name: Release notes
      location: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes
    - name: Release notes1
      location: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.3-Release-Notes1