== Generate a changelog for a GitHub milestone

To generate a markdown changelog that comprise the list of bugs and issues in a GitHub milestone follow these steps:

- Download a https://github.com/spring-io/github-changelog-generator/releases[release JAR] or use the https://hub.docker.com/r/springio/github-changelog-generator/[Docker image].
- Configure the application with the following properties:

[source,yaml]
----
changelog:
  repository: owner/name
github:
  username:
  password:
----

NOTE: When generating a changelog for a public repository, the `username` and `password` properties are optional.
However, specifying them ensures that you don't hit https://developer.github.com/v3/?#rate-limiting[GitHub's rate limit] easily.

If you're using GitHub enterprise, the base url can be set using `github.api-url`.

TIP: If you are only configuring a few properties you can alternatively use application arguments such as `--changelog.repository=...`.

- Run the following commands:

----
$ java -jar github-changelog-generator.jar <milestone> <path_to_generate_file>
----

NOTE: By default `<milestone>` refers to the milestone title.
If you want to use milestone ID, you should set the `changelog.milestone-reference` property to `id`.

=== Customizing Sections
By default the changelog will contain the following sections:

|===
|Title |Label Text

|":star: New Features"
|"enhancement"

|":beetle: Bug Fixes"
|"regression" or "bug"

|":notebook_with_decorative_cover: Documentation"
|"documentation"

|":hammer: Dependency Upgrades"
|"dependency-upgrade"
|===

The title is in https://guides.github.com/features/mastering-markdown[Markdown] format and emoji like ":star:" can be used.
If you want something different then you can add `sections` YAML:

[source,yaml]
----
changelog:
  sections:
  - title: "Enhancements"
    labels: ["new"]
  - title: "Bugs"
    labels: ["fix"]
----

== License
This project is Open Source software released under the
https://www.apache.org/licenses/LICENSE-2.0.html[Apache 2.0 license].

