== Generate release notes for a GitHub milestone

To generate markdown release notes that comprise the list of bugs and issues in a GitHub milestone follow these steps:

- Download a https://github.com/spring-io/github-release-notes-generator/releases[release JAR] or use the https://hub.docker.com/r/springio/github-release-notes-generator/[Docker image].
- Configure the application with the following properties:

[source,yaml]
----
releasenotes:
  github:
    api-url: #defaulted to https://api.github.com
    organization:
    repository:
    username:
    password:
----

NOTE: When generating release notes for a public repository, the `username` and `password` properties are optional.
However, specifying them ensures that you don't hit https://developer.github.com/v3/?#rate-limiting[GitHub's rate limit] easily.

TIP: If you are only configuring a few properties you can alternatively use application arguments such as `--releasenotes.github.organization=...`.

- Run the following commands:

----
$ java -jar github-release-notes-generator.jar <milestone> <path_to_generate_file>
----

NOTE: The `<milestone>` may either refer to the milestone number or a name.

=== Customizing Sections
By default the release notes will contain the following sections:

|===
|Title |Label Text

|New Features
|"enhancement"

|Bug Fixes
|"regression" or "bug"

|Documentation
|"documentation"

|Dependency Upgrades
|"dependency-upgrade"
|===

If you want something different then you can add `sections` YAML:

[source,yaml]
----
releasenotes:
  sections:
  - title: "Enhancements"
    emoji: ":star:"
    labels: ["new"]
  - title: "Bugs"
    emoji: ":beetle:"
    labels: ["fix"]
----

== License
This project is Open Source software released under the
https://www.apache.org/licenses/LICENSE-2.0.html[Apache 2.0 license].

